image:
  repository: b4bz/homer
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: dashy.picluster.dz.pzuj.net
      paths:
        - /
  tls: []

resources: {}
