apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  selector:
    app: uptime-kuma
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
