apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "zabbix.fullname" . }}-postgresql
  namespace: zabbix
  labels:
    {{- include "zabbix.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "zabbix.fullname" . }}-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "zabbix.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "zabbix.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: custom-postgresql-config
          configMap:
            name: custom-postgresql-config
      containers:
        - name: postgresql
          image: "bitnami/postgresql:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: custom-postgresql-config
              mountPath: /bitnami/postgresql/conf/pg_hba.conf
              subPath: pg_hba.conf
          env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "zabbix.fullname" . }}-postgresql
                  key: postgresql-password
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready --host {{ include "zabbix.fullname" . }}-postgresql --port 5432 --username postgres
            initialDelaySeconds: 30
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready --host {{ include "zabbix.fullname" . }}-postgresql --port 5432 --username postgres
            initialDelaySeconds: 5
            timeoutSeconds: 5
