apiVersion: v1
kind: ConfigMap
metadata:
  name: botkube-configmap
  namespace: botkube
data:
  config.yaml: |
    settings:
      clustername: "{{ .Values.config.settings.clustername }}"
      upgradeNotifier: {{ .Values.config.settings.upgradeNotifier }}
      workloadNotifier: {{ .Values.config.settings.workloadNotifier }}
    resources:
      - name: "{{ .Values.config.resources[0].name }}"
        namespaces:
          include:
            {{- toYaml .Values.config.resources[0].namespaces.include | nindent 12 }}
        events:
          {{- range .Values.config.resources[0].events }}
          - {{ . }}
          {{- end }}
    communications:
      discord:
        enabled: {{ .Values.communications.discord.enabled }}
        secret:
          name: "{{ .Values.communications.discord.secret.name }}"
          key: "{{ .Values.communications.discord.secret.key }}"
        channel: "{{ .Values.communications.discord.channel }}"
        notifType: "{{ .Values.communications.discord.notifType }}"
