apiVersion: v1
kind: ConfigMap
metadata:
  name: botkube-configmap
  namespace: botkube
data:
  resource_config.yaml: |
    kubectl:
      enabled: {{ .Values.config.executors.kubectl.enabled | default "false" }}
      config: "/kubeconfig"
    resources:
      namespaces:
        include:
          {{- range .Values.config.resources.namespaces.include }}
          - {{ . }}
          {{- end }}
        ignore:
          {{- range .Values.config.resources.namespaces.ignore }}
          - {{ . }}
          {{- end }}
      events:
        include:
          {{- range .Values.config.resources.events.include }}
          - {{ . }}
          {{- end }}
  comm_config.yaml: |
    discord:
      enabled: {{ .Values.config.communications.discord.enabled | default "false" }}
      secret:
        name: "{{ .Values.config.communications.discord.secret.name }}"
        key: "{{ .Values.config.communications.discord.secret.key }}"
      channel: "{{ .Values.config.communications.discord.channel }}"
      notifType: "{{ .Values.config.communications.discord.notifType }}"
