apiVersion: v1
kind: ConfigMap
metadata:
  name: botkube-configmap
  namespace: botkube
data:
  config.yaml: |
    settings:
      clustername: "{{ .Values.config.settings.clustername }}"
      upgradeNotifier: {{ .Values.config.settings.upgradeNotifier | default "false" }}
      workloadNotifier: {{ .Values.config.settings.workloadNotifier | default "false" }}
    resources:
      {{- range .Values.config.resources }}
      - name: "{{ .name }}"
        namespaces:
          include:
            {{ toYaml .namespaces.include | indent 12 }}
        events:
          {{ toYaml .events | indent 12 }}
      {{- end }}
    communications:
      discord:
        enabled: {{ .Values.communications.discord.enabled }}
        secret:
          name: "{{ .Values.communications.discord.secret.name }}"
          key: "{{ .Values.communications.discord.secret.key }}"
        channel: "{{ .Values.communications.discord.channel }}"
        notifType: "{{ .Values.communications.discord.notifType }}"
    executors:
      kubectl:
        enabled: {{ .Values.executors.kubectl.enabled | default "false" }}
    plugins:
      botkube.echo:
        enabled: {{ .Values.plugins.botkube.echo.enabled | default "false" }}
    analytics:
      reportErrors: {{ .Values.analytics.reportErrors | default "false" }}
      reportUsage: {{ .Values.analytics.reportUsage | default "false" }}
