apiVersion: v1
kind: ConfigMap
metadata:
  name: botkube-configmap
  namespace: botkube
data:
  resource_config.yaml: |
    {{ .Files.Get "files/resource_config.yaml" | indent 4 }}
  comm_config.yaml: |
    {{ .Files.Get "files/comm_config.yaml" | indent 4 }}
