apiVersion: v1
kind: ConfigMap
metadata:
  name: botkube-configmap
  namespace: botkube
data:
  config.yaml: |
    settings:
      clustername: "{{ .Values.config.settings.clustername }}"
      upgradeNotifier: {{ .Values.config.settings.upgradeNotifier | toYaml | nindent 8 }}
      workloadNotifier: {{ .Values.config.settings.workloadNotifier | toYaml | nindent 8 }}
    resources:
      - name: "{{ .Values.config.resources[0].name }}"
        namespaces:
          include:
            {{- range .Values.config.resources[0].namespaces.include }}
            - "{{ . }}"
            {{- end }}
        events:
          {{- range .Values.config.resources[0].events }}
          - "{{ . }}"
          {{- end }}
