apiVersion: apps/v1
kind: Deployment
metadata:
  name: botkube
  namespace: botkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: botkube
  template:
    metadata:
      labels:
        app: botkube
    spec:
      serviceAccountName: botkube-sa
      containers:
        - name: botkube
          image: "infracloudio/botkube:latest"
          env:
            - name: CONFIG_FILE_PATH
              value: "/config.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /config.yaml
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: botkube-configmap
