apiVersion: apps/v1
kind: Deployment
metadata:
  name: botkube
  namespace: botkube
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Ensure ConfigMap is created before this deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: botkube
  template:
    metadata:
      labels:
        app: botkube
    spec:
      serviceAccountName: botkube-sa
      containers:
        - name: botkube
          image: "raspbernetes/botkube:latest"
          env:
            - name: CONFIG_FILE_PATH
              value: "/config/comm_config.yaml"
            - name: RESOURCE_FILE_PATH
              value: "/config/resource_config.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: botkube-configmap
      startupProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 30
        periodSeconds: 10
