apiVersion: apps/v1
kind: Deployment
metadata:
  name: botkube
  namespace: botkube
  labels:
    app: botkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: botkube
  template:
    metadata:
      labels:
        app: botkube
    spec:
      serviceAccountName: botkube-sa
      containers:
        - name: botkube
          image: raspbernetes/botkube:latest
          env:
            - name: CONFIG_FILE_PATH
              value: "/files/comm_config.yaml"
            - name: RESOURCE_FILE_PATH
              value: "/files/resource_config.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /files/comm_config.yaml
              subPath: comm_config.yaml
            - name: resource-config-volume
              mountPath: /files/resource_config.yaml
              subPath: resource_config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: botkube-configmap
            items:
              - key: comm_config.yaml
                path: comm_config.yaml
        - name: resource-config-volume
          configMap:
            name: botkube-configmap
            items:
              - key: resource_config.yaml
                path: resource_config.yaml
