apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "botkube.fullname" . }}
  labels:
    {{ include "botkube.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ include "botkube.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "botkube.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: botkube
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CONFIG_FILE_PATH
              value: "/files/comm_config.yaml"
            - name: RESOURCE_FILE_PATH
              value: "/files/resource_config.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /files/comm_config.yaml
              subPath: comm_config.yaml
            - name: resource-config-volume
              mountPath: /files/resource_config.yaml
              subPath: resource_config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: botkube-configmap
            items:
              - key: comm_config.yaml
                path: comm_config.yaml
        - name: resource-config-volume
          configMap:
            name: botkube-configmap
            items:
              - key: resource_config.yaml
                path: resource_config.yaml
