apiVersion: apps/v1
kind: Deployment
metadata:
  name: botkube
  namespace: botkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: botkube
  template:
    metadata:
      labels:
        app: botkube
    spec:
      containers:
        - name: botkube
          image: "raspbernetes/botkube:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: CONFIG_FILE_PATH
              value: "/files/botkube-config.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /files/botkube-config.yaml
              subPath: botkube-config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: botkube-configmap
            items:
              - key: botkube-config.yaml
                path: botkube-config.yaml
