# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "botkube.fullname" . }}
  labels:
    app: {{ include "botkube.name" . }}
    chart: {{ include "botkube.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

---
# ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "botkube.fullname" . }}
  labels:
    app: {{ include "botkube.name" . }}
    chart: {{ include "botkube.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"]


---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "botkube.fullname" . }}
  labels:
    app: {{ include "botkube.name" . }}
    chart: {{ include "botkube.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "botkube.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "botkube.fullname" . }}
    namespace: {{ .Release.Namespace }}


