# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "botkube.fullname" . }}
  labels:
    app: {{ include "botkube.name" . }}
    chart: {{ include "botkube.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

---
# ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: botkube-role
  namespace: botkube
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]

---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: botkube-rolebinding
  namespace: botkube
subjects:
  - kind: ServiceAccount
    name: botkube-sa
    namespace: botkube
roleRef:
  kind: Role
  name: botkube-role
  apiGroup: rbac.authorization.k8s.io

