# resource_config.yaml

# Configuration for kubectl command execution
kubectl:
  enabled: true
  config: "/kubeconfig"  # Ensure this path matches the actual location of your kubeconfig

# Namespaces to include or ignore
resources:
  namespaces:
    include:
      - default
      - kube-system
    ignore:
      - kube-public
      - kube-node-lease

  events:
    include:
      - create
      - delete
      - error
      - update
