apiVersion: v1
kind: Service
metadata:
  name: botkube-service
  namespace: botkube
spec:
  selector:
    app: botkube
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
