master:
  image: "jenkins/jenkins"
  tag: "latest"
  imagePullPolicy: "Always"
  service:
    type: LoadBalancer
    port: 8080
    targetPort: 8080
    loadBalancerIP: 192.168.68.211  
  resources:
    limits:
      cpu: "2"
      memory: "4Gi"
    requests:
      cpu: "1"
      memory: "2Gi"
  persistentVolumeClaim:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 16Gi
    storageClassName: longhorn  
adminPassword: Q2hlZXNlMjNTdHJpbmdz
