apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portainer-sa-clusteradmin-crb
subjects:
- kind: ServiceAccount
  name: portainer-sa-clusteradmin
  namespace: portainer
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
