apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "portainer.fullname" . }}-pvc
  labels:
    app.kubernetes.io/name: {{- include "portainer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClass }}
