apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  namespace: homer
  labels:
    app: homer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      annotations:
      labels:
        app: homer
    spec:
      serviceAccountName: default
      securityContext: {}
      containers:
        - name: homer
          securityContext: {}
          image: "b4bz/homer:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /www/config/config.yml
              subPath: config.yml
      volumes:
        - name: config-volume
          configMap:
            name: homer-config
      nodeSelector: {}
      affinity: {}
      tolerations: []
