apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-homer
  namespace: homer
  labels:
    app: homer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      labels:
        app: homer
    spec:
      containers:
        - name: homer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /www/assets
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-config
