apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer
  namespace: homer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: longhorn