apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-homer
  annotations:
    metallb.universe.tf/address-pools: default
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.68.210
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: homer
