apiVersion: v2
name: zabbix
description: A Helm chart for Kubernetes


dependencies:
  - name: postgresql
    version: "15.5.20"
    repository: "https://charts.bitnami.com/bitnami"

type: application
version: 0.1.0
appVersion: "1.0"
