replicaCount: 1

image:
  repository: zabbix/zabbix-server-pgsql
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: DB_SERVER_HOST
    value: postgresql
  - name: DB_SERVER_PORT
    value: "5432"
  - name: DB_SERVER_DBNAME
    value: zabbix
  - name: DB_SERVER_SCHEMA
    value: public

service:
  type: LoadBalancer
  port: 8080


persistence:
  enabled: true
  storageClass: longhorn
  accessModes:
    - ReadWriteOnce
  size: 10Gi
