global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""
  zabbixDatabaseHost: {{ include "zabbix.fullname" . }}-postgresql

replicaCount: 1

image:
  repository: zabbix/zabbix-server-pgsql
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 10051
  targetPort: 10051
  loadBalancerIP: 192.168.68.212

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: zabbix.picluster.dz.pzuj.net
      paths:
        - /

resources: {}
persistence:
  enabled: true
  storageClass: longhorn
  accessMode: ReadWriteOnce
  size: 8Gi

zabbix:
  server:
    env:
      - name: DB_SERVER_HOST
        value: {{ include "zabbix.fullname" . }}-postgresql
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: zabbix-postgresql
            key: postgresql-username
      - name: POSTGRES_PASSWORD
