global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""
  zabbixDatabaseHost: zabbix-postgresql

# Zabbix configuration
replicaCount: 1

image:
  repository: zabbix/zabbix-server-pgsql
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 10051
  targetPort: 10051
  loadBalancerIP: 192.168.68.212

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: zabbix.picluster.dz.pzuj.net
      paths:
        - /

resources: {}
persistence:
  enabled: true
  storageClass: longhorn
  accessMode: ReadWriteOnce
  size: 8Gi

zabbix:
  server:
    env:
      - name: DB_SERVER_HOST
        value: zabbix-postgresql
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: zabbix-postgresql
            key: postgresql-username
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: zabbix-postgresql
            key: postgresql-password
      - name: POSTGRES_DB
        valueFrom:
          secretKeyRef:
            name: zabbix-postgresql
            key: postgresql-database
  web:
    image:
      repository: zabbix/zabbix-web-nginx-pgsql
      tag: "latest"
      pullPolicy: IfNotPresent
    resources: {}
  agent:
    image:
      repository: zabbix/zabbix-agent
      tag: "latest"
      pullPolicy: IfNotPresent
    resources: {}

# PostgreSQL configuration
postgresql:
  enabled: true
  existingSecret: zabbix-postgresql
  primary:
    image:
      repository: bitnami/postgresql
      tag: "latest"
      pullPolicy: IfNotPresent
    resources: {}
