replicaCount: 1

image:
  repository: zabbix/zabbix-server-pgsql
  tag: "latest"
  pullPolicy: IfNotPresent

postgresql:
  image:
    repository: bitnami/postgresql
    tag: "latest"
    pullPolicy: IfNotPresent
  postgresqlUsername: zabbix
  postgresqlPassword: zabbixpass
  postgresqlDatabase: zabbix

service:
  type: ClusterIP
  port: 10051

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: zabbix.local
      paths:
        - /

resources: {}
persistence:
  enabled: true
  storageClass: longhorn
  accessMode: ReadWriteOnce
  size: 8Gi
