apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dashy
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: homer
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/homer
    repoURL: 'https://github.com/Eclesion/k3s.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  helm:
    parameters:
      - name: service.loadBalancerIP
        value: 192.168.68.210
      - name: 'ingress.hosts[0].host'
        value: dashy.picluster.dz.pzuj.net
