apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dashy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Eclesion/k3s.git'
    targetRevision: main
    path: charts/dashy
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: homer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  helm:
    parameters:
      - name: service.loadBalancerIP
        value: '192.168.68.210'
      - name: ingress.hosts[0].host
        value: 'dashy.picluster.dz.pzuj.net'
      - name: ingress.hosts[0].paths[0]
        value: '/'
