apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: zabbix
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/postgresql
    repoURL: 'https://github.com/eclesion/k3s.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

