apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/eclesion/k3s.git'
    targetRevision: HEAD
    path: charts/postgresql
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: zabbix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
