apiVersion: v2
name: postgresql
description: A Helm chart for PostgreSQL
type: application
version: 0.1.0
appVersion: latest
dependencies:
  - name: postgresql
    version: 12.8.3
    repository: https://charts.bitnami.com/bitnami
