apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zabbix.fullname" . }}-postgresql
  labels:
    app: {{ include "zabbix.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "zabbix.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "zabbix.name" . }}
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.postgresqlDatabase }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "zabbix.fullname" . }}-postgresql
