apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zabbix.fullname" . }}-postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: {{ .Values.persistence.storageClass }}
