apiVersion: v1
kind: Service
metadata:
  name: {{ include "zabbix.fullname" . }}-postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ include "zabbix.name" . }}
