apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgresql.name" . }}-pvc
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  storageClassName: longhorn
