apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgresql-rolebinding
  namespace: zabbix
subjects:
- kind: ServiceAccount
  name: default
  namespace: zabbix
roleRef:
  kind: Role
  name: postgresql-role
  apiGroup: rbac.authorization.k8s.io
