apiVersion: v1
kind: Pod
metadata:
  name: temp-busybox
  namespace: zabbix
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - name: data
      mountPath: /bitnami/postgresql
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: postgresql-pvc
