apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homer-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Eclesion/k3s'
    targetRevision: HEAD
    path: 'homer'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  hooks:
  - name: update-configmap
    type: PreSync
    properties:
      syncPolicy:
        automated: true
    spec:
      source:
        repoURL: 'https://github.com/Eclesion/k3s'
        targetRevision: HEAD
        path: 'homer/sync-hook-job.yml'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
