apiVersion: v1
kind: Service
metadata:
  name: homer
spec:
  selector:
    app: homer
  type: LoadBalancer
  ports:
    - name: homer
      protocol: TCP
      port: 8080
      targetPort: 8080
  loadBalancerIP: 192.168.68.210
