apiVersion: batch/v1
kind: Job
metadata:
  name: update-configmap
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: update-configmap
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting ConfigMap update job"
          kubectl create configmap homer-config --from-file=config.yml=/path/to/config.yml --dry-run=client -o yaml
          kubectl create configmap homer-config --from-file=config.yml=/path/to/config.yml --dry-run=client -o yaml | kubectl apply -f -
        env:
        - name: KUBECONFIG
          value: /root/.kube/config  # Ensure this path is correct
      restartPolicy: OnFailure
