apiVersion: batch/v1
kind: Job
metadata:
  name: update-configmap
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: update-configmap
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting ConfigMap update job"
          kubectl create configmap homer-config --from-file=config.yml=/www/assets/config.yml --dry-run=client -o yaml | kubectl apply -f -
      serviceAccountName: default  # Use the default service account
      restartPolicy: OnFailure
