config:
  settings:
    clustername: picluster
    upgradeNotifier: true
    workloadNotifier: true

  resources:
    - name: "all-resources"
      namespaces:
        include:
          - "all"
      events:
        - create
        - delete
        - error
        - update
