config:
  image:
    repository: "raspbernetes/botkube"
    tag: "latest"
    pullPolicy: "IfNotPresent"
  settings:
    clustername: "picluster"
    upgradeNotifier: true
    workloadNotifier: true
  communications:
    discord:
      enabled: true
      secret:
        name: "botkube-discord-secret"
        key: "botToken"
      channel: "1188268010394374234"
      notifType: "short"
  resources:
    - name: "all-resources"
      namespaces:
        include:
          - default
          - kube-system
        ignore:
          - kube-public
          - kube-node-lease
      events:
        - create
        - delete
        - error
        - update
  executors:
    kubectl:
      enabled: true
      config: "/kubeconfig"
  plugins:
    botkubeecho:
      enabled: true
  analytics:
    reportErrors: true
    reportUsage: true
log:
  level: "debug"
