apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "zabbix.fullname" . }}-postgresql
  namespace: zabbix
  labels:
    app: {{ template "zabbix.name" . }}
    chart: {{ template "zabbix.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.postgresql.primary.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.postgresql.primary.persistence.size | default "8Gi" }}
  storageClassName: {{ .Values.postgresql.primary.persistence.storageClass | default "longhorn" }}
