apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-postgresql
  namespace: zabbix
  labels:
    app: zabbix
    chart: zabbix-0.1.0
    release: my-release
    heritage: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn
