apiVersion: v1
kind: Secret
metadata:
  name: zabbix-postgresql
  namespace: zabbix
type: Opaque
data:
  postgresql-username: emFiYml4  # base64 encoded 'zabbix'
  postgresql-password: emFiYml4cGFzcw==  # base64 encoded 'zabbixpass'
  postgresql-database: emFiYml4  # base64 encoded 'zabbix'