replicaCount: 1

image:
  repository: bitnami/postgresql
  tag: 13.15.0

service:
  type: ClusterIP
  port: 5432

postgresql:
  username: zabbix
  database: zabbix
  existingSecret: postgresql-secret
  secretKeys:
    password: POSTGRESQL_PASSWORD

persistence:
  enabled: true
  storageClass: longhorn
  accessModes:
    - ReadWriteOnce
  size: 32Gi

extraEnvVars:
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgresql-secret
        key: POSTGRES_PASSWORD
  - name: POSTGRESQL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgresql-secret
        key: POSTGRESQL_PASSWORD

initdbScripts:
  custom_pg_hba_conf.sh: |
    #!/bin/bash
    echo "host    all             all             0.0.0.0/0               md5" >> /opt/bitnami/postgresql/conf/pg_hba.conf
