replicaCount: 1

image:
  repository: bitnami/postgresql
  tag: 13.15.0

service:
  type: ClusterIP
  port: 5432

postgresql:
  username: zabbix
  database: zabbix
  existingSecret: postgresql-secret
  secretKeys:
    password: POSTGRESQL_PASSWORD
  customConfig: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    host    all             all             0.0.0.0/0               md5

persistence:
  enabled: true
  storageClass: longhorn
  accessModes:
    - ReadWriteOnce
  size: 32Gi

extraEnv:
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgresql-secret
        key: POSTGRES_PASSWORD
  - name: POSTGRESQL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgresql-secret
        key: POSTGRESQL_PASSWORD
