replicaCount: 1

image:
  repository: bitnami/postgresql
  tag: latest

service:
  type: ClusterIP
  port: 5432

postgresql:
  username: postgres
  database: postgres
  existingSecret: postgresql-secret
  secretKeys:
    password: POSTGRES_PASSWORD
  securityContext:
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001

persistence:
  enabled: true
  existingClaim: postgresql-pvc
  storageClass: longhorn
  accessModes:
    - ReadWriteOnce
  size: 32Gi

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

extraEnvVars:
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgresql-secret
        key: POSTGRES_PASSWORD
  - name: ZABBIX_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgresql-secret
        key: ZABBIX_DB_PASSWORD

initContainers:
  - name: init-postgres
    image: busybox
    command: ['sh', '-c', '
      # Fix permissions on the data directory
      chown -R 1001:1001 /bitnami/postgresql;
      
      # Create a custom pg_hba.conf file if needed
      if [ ! -f /bitnami/postgresql/conf/pg_hba.conf ]; then
        echo "host    all             all             0.0.0.0/0               md5" > /bitnami/postgresql/conf/pg_hba.conf;
      fi
    ']
    volumeMounts:
      - name: data
        mountPath: /bitnami/postgresql

livenessProbe:
  httpGet:
    path: /health
    port: 5432
  initialDelaySeconds: 30
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /health
    port: 5432
  initialDelaySeconds: 30
  timeoutSeconds: 5
