replicaCount: 1

image:
  repository: bitnami/postgresql
  tag: 13.15.0


service:
  type: ClusterIP
  port: 5432

postgresql:
  username: zabbix
  database: zabbix

persistence:
  enabled: true
  storageClass: longhorn
  accessModes:
    - ReadWriteOnce
  size: 32Gi