replicaCount: 1

image:
  repository: bitnami/postgresql
  tag: latest

service:
  type: ClusterIP
  port: 5432

postgresql:
  username: zabbix
  database: zabbix
  existingSecret: postgresql-secret
  secretKeys:
    password: POSTGRESQL_PASSWORD
  securityContext:
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001

persistence:
  enabled: true
  existingClaim: postgresql-pvc
  storageClass: longhorn
  accessModes:
    - ReadWriteOnce
  size: 32Gi

extraEnvVars:
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgresql-secret
        key: POSTGRES_PASSWORD
  - name: POSTGRESQL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgresql-secret
        key: POSTGRESQL_PASSWORD

customConfig: |
  # TYPE  DATABASE        USER            ADDRESS                 METHOD
  host    all             all             0.0.0.0/0               md5


initContainers:
  - name: fix-permissions
    image: busybox
    command: ["sh", "-c", "chown -R 1001:1001 /bitnami/postgresql"]
    volumeMounts:
      - name: data
        mountPath: /bitnami/postgresql


volumeMounts:
  - name: data
    mountPath: /bitnami/postgresql
volumes:
  - name: data
    persistentVolumeClaim:
      claimName: postgresql-pvc


#-Alternative to customConfig-
#initdbScripts:
#  custom_pg_hba_conf.sh: |
#    #!/bin/bash
#    echo "host    all             all             0.0.0.0/0               md5" >> /opt/bitnami/postgresql/conf/pg_hba.conf
