# Configuration for Discord integration
communications:
  discord:
    enabled: true
    secret:
      name: "botkube-discord-secret"
      key: "botToken"
    channel: "1188268010394374234"
    notifType: "short"
