apiVersion: v1
kind: Service
metadata:
  name: dashy-homer
  namespace: homer
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.68.210
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: dashy
