apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix
  namespace: zabbix
  labels:
    app.kubernetes.io/name: zabbix
    app.kubernetes.io/instance: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zabbix
      app.kubernetes.io/instance: zabbix
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zabbix
        app.kubernetes.io/instance: zabbix
    spec:
      containers:
        - name: zabbix
          image: "zabbix/zabbix-server-pgsql:latest"
          ports:
            - containerPort: 8080
          env:
            - name: DB_SERVER_HOST
              value: postgresql
            - name: DB_SERVER_PORT
              value: "5432"
            - name: DB_SERVER_DBNAME
              value: zabbix
            - name: DB_SERVER_SCHEMA
              value: public
          volumeMounts:
            - name: zabbix-data
              mountPath: /var/lib/zabbix
      volumes:
        - name: zabbix-data
          persistentVolumeClaim:
            claimName: zabbix-pvc
