apiVersion: v1
kind: Service
metadata:
  name: zabbix-service
  namespace: zabbix
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.68.212
  selector:
    app.kubernetes.io/name: zabbix
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
