apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-postgresql
  namespace: zabbix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn
