apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zabbix.fullname" . }}
  namespace: zabbix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
