apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zabbix.fullname" . }}
  namespace: zabbix
  labels:
    app: {{ include "zabbix.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "zabbix.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "zabbix.name" . }}
    spec:
      containers:
        - name: zabbix
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_SERVER_HOST
              value: {{ include "zabbix.fullname" . }}-postgresql
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.postgresqlDatabase }}
          ports:
            - containerPort: 10051
          volumeMounts:
            - name: data
              mountPath: /var/lib/zabbix
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "zabbix.fullname" . }}
