apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: zabbix
  labels:
    app: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix
  template:
    metadata:
      labels:
        app: zabbix
    spec:
      containers:
        - name: zabbix
          image: bitnami/zabbix-server-pgsql:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_SERVER_HOST
              value: zabbix-postgresql
            - name: POSTGRES_USER
              value: zabbix_user
            - name: POSTGRES_PASSWORD
              value: zabbix_password
            - name: POSTGRES_DB
              value: zabbix_db
          ports:
            - containerPort: 10051
          volumeMounts:
            - name: data
              mountPath: /var/lib/zabbix
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: zabbix-server
