---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/eclesion

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/r/homelab

- Music:
    - YouTube Music:
        - abbr: YTM
          href: https://music.youtube.com/
- Video:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
- Icons:
    -Selfhost Icons:
        - abbr: SH
          href: https://selfh.st/icons/
    -Simple Icons:
        - abbr: SI
          href: https://simpleicons.org
    -Material Design Icons:
        - abbr: MDI
          href: https://pictogrammers.com/library/mdi/
    -Dashboard Icons:
        - abbr: DI
          href: https://dashboardicons.com/
    -Emoji Combos:
        - abbr: EC
          href: https://emojicombos.com/
