---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: [brave, google, duckduckgo]
    focus: true
    showSearchSuggestions: true
    target: _blank

- datetime:
    text_size: xl
    format:
      timeStyle: short

- openmeteo:
    label: Wien
    latitude: 48.2085
    longitude: 16.3721
    timezone: Europe/Vienna
    units: metric
    cache: 5
    format:
      maximumFractionDigits: 1
