apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jenkins.name" . }}-config
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
data:
  jenkins-config.yaml: |-
    jenkins:
      systemMessage: "Welcome to Jenkins configured by Helm!"
