apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jenkins.name" . }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "jenkins.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "jenkins.name" . }}
    spec:
      serviceAccountName: jenkins-sa
      initContainers:
        - name: init-permissions
          image: busybox
          command: ['sh', '-c', 'mkdir -p /var/jenkins_home && chown -R 1000:1000 /var/jenkins_home']
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      containers:
        - name: jenkins
          image: {{ .Values.master.image }}:{{ .Values.master.tag }}
          imagePullPolicy: {{ .Values.master.imagePullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.master.resources | nindent 12 }}
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
              subPath: jenkins-home
          securityContext:
            runAsUser: 1000
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: {{ include "jenkins.name" . }}-pvc