apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.name" . }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  type: {{ .Values.master.service.type }}
  ports:
    - port: {{ .Values.master.service.port }}
      targetPort: {{ .Values.master.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ include "jenkins.name" . }}
  loadBalancerIP: {{ .Values.master.service.loadBalancerIP }}
