apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jenkins.name" . }}-admin-secret
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
type: Opaque
data:
  jenkins-admin-password: {{ .Values.adminPassword | quote }}
