apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jenkins.name" . }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "jenkins.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "jenkins.name" . }}
    spec:
      serviceAccountName: jenkins-sa
      initContainers:
        - name: init-permissions
          image: ubuntu:latest
          command: ['sh', '-c', 'apt-get update && apt-get install -y gcc g++ python3 python3-pip ruby-full openjdk-11-jdk docker.io && apt-get clean && mkdir -p /var/jenkins_home /var/jenkins_backup && chown -R 1000:1000 /var/jenkins_home /var/jenkins_backup && chmod -R 775 /var/jenkins_home /var/jenkins_backup']
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: jenkins-backup
              mountPath: /var/jenkins_backup
      containers:
        - name: jenkins
          image: {{ .Values.master.image }}:{{ .Values.master.tag }}
          imagePullPolicy: {{ .Values.master.imagePullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.master.resources | nindent 12 }}
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: jenkins-backup
              mountPath: /var/jenkins_backup
          securityContext:
            runAsUser: 1000
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: {{ include "jenkins.name" . }}-pvc
        - name: jenkins-backup
          persistentVolumeClaim:
            claimName: jenkins-backup-pvc
