---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-backup-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn